# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addmenus.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_EkleMenu(object):
    def setupUi(self, EkleMenu):
        EkleMenu.setObjectName("EkleMenu")
        EkleMenu.resize(300, 400)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/keçi.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        EkleMenu.setWindowIcon(icon)
        self.verticalLayout = QtWidgets.QVBoxLayout(EkleMenu)
        self.verticalLayout.setContentsMargins(-1, 30, -1, 30)
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.keciekle = QtWidgets.QPushButton(EkleMenu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.keciekle.sizePolicy().hasHeightForWidth())
        self.keciekle.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.keciekle.setFont(font)
        self.keciekle.setObjectName("keciekle")
        self.verticalLayout.addWidget(self.keciekle)
        self.asimekle = QtWidgets.QPushButton(EkleMenu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.asimekle.sizePolicy().hasHeightForWidth())
        self.asimekle.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.asimekle.setFont(font)
        self.asimekle.setObjectName("asimekle")
        self.verticalLayout.addWidget(self.asimekle)
        self.sutekle = QtWidgets.QPushButton(EkleMenu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sutekle.sizePolicy().hasHeightForWidth())
        self.sutekle.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.sutekle.setFont(font)
        self.sutekle.setObjectName("sutekle")
        self.verticalLayout.addWidget(self.sutekle)
        self.kiloekle = QtWidgets.QPushButton(EkleMenu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.kiloekle.sizePolicy().hasHeightForWidth())
        self.kiloekle.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.kiloekle.setFont(font)
        self.kiloekle.setObjectName("kiloekle")
        self.verticalLayout.addWidget(self.kiloekle)
        self.hastalikekle = QtWidgets.QPushButton(EkleMenu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hastalikekle.sizePolicy().hasHeightForWidth())
        self.hastalikekle.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.hastalikekle.setFont(font)
        self.hastalikekle.setObjectName("hastalikekle")
        self.verticalLayout.addWidget(self.hastalikekle)
        self.asiekle = QtWidgets.QPushButton(EkleMenu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.asiekle.sizePolicy().hasHeightForWidth())
        self.asiekle.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.asiekle.setFont(font)
        self.asiekle.setObjectName("asiekle")
        self.verticalLayout.addWidget(self.asiekle)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.mainmenubuton = QtWidgets.QPushButton(EkleMenu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mainmenubuton.sizePolicy().hasHeightForWidth())
        self.mainmenubuton.setSizePolicy(sizePolicy)
        self.mainmenubuton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/home.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mainmenubuton.setIcon(icon1)
        self.mainmenubuton.setIconSize(QtCore.QSize(32, 32))
        self.mainmenubuton.setObjectName("mainmenubuton")
        self.horizontalLayout.addWidget(self.mainmenubuton)
        self.exitbuton = QtWidgets.QPushButton(EkleMenu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.exitbuton.sizePolicy().hasHeightForWidth())
        self.exitbuton.setSizePolicy(sizePolicy)
        self.exitbuton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icons/exits.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.exitbuton.setIcon(icon2)
        self.exitbuton.setIconSize(QtCore.QSize(32, 32))
        self.exitbuton.setObjectName("exitbuton")
        self.horizontalLayout.addWidget(self.exitbuton)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(EkleMenu)
        QtCore.QMetaObject.connectSlotsByName(EkleMenu)

    def retranslateUi(self, EkleMenu):
        _translate = QtCore.QCoreApplication.translate
        EkleMenu.setWindowTitle(_translate("EkleMenu", "Ekle Menüsü"))
        self.keciekle.setText(_translate("EkleMenu", "Keçi Ekle"))
        self.asimekle.setText(_translate("EkleMenu", "Aşım Tarihi Ekle/Güncelle"))
        self.sutekle.setText(_translate("EkleMenu", "Süt Verimi Ekle"))
        self.kiloekle.setText(_translate("EkleMenu", "Kilo Bilgisi Ekle"))
        self.hastalikekle.setText(_translate("EkleMenu", "Hastalık Durumu Ekle"))
        self.asiekle.setText(_translate("EkleMenu", "Aşı Durumu Ekle"))
