# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'editmenus.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DuzenleMenu(object):
    def setupUi(self, DuzenleMenu):
        DuzenleMenu.setObjectName("DuzenleMenu")
        DuzenleMenu.resize(300, 400)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/keçi.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        DuzenleMenu.setWindowIcon(icon)
        self.verticalLayout = QtWidgets.QVBoxLayout(DuzenleMenu)
        self.verticalLayout.setContentsMargins(-1, 30, -1, 30)
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.keciduzenle = QtWidgets.QPushButton(DuzenleMenu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.keciduzenle.sizePolicy().hasHeightForWidth())
        self.keciduzenle.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.keciduzenle.setFont(font)
        self.keciduzenle.setObjectName("keciduzenle")
        self.verticalLayout.addWidget(self.keciduzenle)
        self.sutduzenle = QtWidgets.QPushButton(DuzenleMenu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sutduzenle.sizePolicy().hasHeightForWidth())
        self.sutduzenle.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.sutduzenle.setFont(font)
        self.sutduzenle.setObjectName("sutduzenle")
        self.verticalLayout.addWidget(self.sutduzenle)
        self.kiloduzenle = QtWidgets.QPushButton(DuzenleMenu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.kiloduzenle.sizePolicy().hasHeightForWidth())
        self.kiloduzenle.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.kiloduzenle.setFont(font)
        self.kiloduzenle.setObjectName("kiloduzenle")
        self.verticalLayout.addWidget(self.kiloduzenle)
        self.hastalikduzenle = QtWidgets.QPushButton(DuzenleMenu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hastalikduzenle.sizePolicy().hasHeightForWidth())
        self.hastalikduzenle.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.hastalikduzenle.setFont(font)
        self.hastalikduzenle.setObjectName("hastalikduzenle")
        self.verticalLayout.addWidget(self.hastalikduzenle)
        self.asiduzenle = QtWidgets.QPushButton(DuzenleMenu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.asiduzenle.sizePolicy().hasHeightForWidth())
        self.asiduzenle.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.asiduzenle.setFont(font)
        self.asiduzenle.setObjectName("asiduzenle")
        self.verticalLayout.addWidget(self.asiduzenle)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.mainmenubuton = QtWidgets.QPushButton(DuzenleMenu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mainmenubuton.sizePolicy().hasHeightForWidth())
        self.mainmenubuton.setSizePolicy(sizePolicy)
        self.mainmenubuton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/home.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mainmenubuton.setIcon(icon1)
        self.mainmenubuton.setIconSize(QtCore.QSize(32, 32))
        self.mainmenubuton.setObjectName("mainmenubuton")
        self.horizontalLayout.addWidget(self.mainmenubuton)
        self.exitbuton = QtWidgets.QPushButton(DuzenleMenu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.exitbuton.sizePolicy().hasHeightForWidth())
        self.exitbuton.setSizePolicy(sizePolicy)
        self.exitbuton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icons/exits.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.exitbuton.setIcon(icon2)
        self.exitbuton.setIconSize(QtCore.QSize(32, 32))
        self.exitbuton.setObjectName("exitbuton")
        self.horizontalLayout.addWidget(self.exitbuton)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(DuzenleMenu)
        QtCore.QMetaObject.connectSlotsByName(DuzenleMenu)

    def retranslateUi(self, DuzenleMenu):
        _translate = QtCore.QCoreApplication.translate
        DuzenleMenu.setWindowTitle(_translate("DuzenleMenu", "Düzenle Menüsü"))
        self.keciduzenle.setText(_translate("DuzenleMenu", "Keçi Bilgileri Düzenle"))
        self.sutduzenle.setText(_translate("DuzenleMenu", "Süt Verimi Düzenle"))
        self.kiloduzenle.setText(_translate("DuzenleMenu", "Kilo Bilgisi Düzenle"))
        self.hastalikduzenle.setText(_translate("DuzenleMenu", "Hastalık Bilgisi Düzenle"))
        self.asiduzenle.setText(_translate("DuzenleMenu", "Aşı Durumu Düzenle"))
