# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'hastaliksilmes.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_HastalikSilme(object):
    def setupUi(self, HastalikSilme):
        HastalikSilme.setObjectName("HastalikSilme")
        HastalikSilme.resize(645, 400)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/keçi.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        HastalikSilme.setWindowIcon(icon)
        self.gridLayout = QtWidgets.QGridLayout(HastalikSilme)
        self.gridLayout.setHorizontalSpacing(9)
        self.gridLayout.setVerticalSpacing(20)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(HastalikSilme)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 2)
        self.result = QtWidgets.QLabel(HastalikSilme)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(15)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.result.setFont(font)
        self.result.setText("")
        self.result.setObjectName("result")
        self.gridLayout.addWidget(self.result, 7, 0, 1, 2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.acceptbuton = QtWidgets.QPushButton(HastalikSilme)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.acceptbuton.sizePolicy().hasHeightForWidth())
        self.acceptbuton.setSizePolicy(sizePolicy)
        self.acceptbuton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/tick.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.acceptbuton.setIcon(icon1)
        self.acceptbuton.setIconSize(QtCore.QSize(64, 64))
        self.acceptbuton.setObjectName("acceptbuton")
        self.horizontalLayout.addWidget(self.acceptbuton)
        self.refreshbuton = QtWidgets.QPushButton(HastalikSilme)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.refreshbuton.sizePolicy().hasHeightForWidth())
        self.refreshbuton.setSizePolicy(sizePolicy)
        self.refreshbuton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icons/refresh.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.refreshbuton.setIcon(icon2)
        self.refreshbuton.setIconSize(QtCore.QSize(64, 64))
        self.refreshbuton.setObjectName("refreshbuton")
        self.horizontalLayout.addWidget(self.refreshbuton)
        self.mainmenubuton = QtWidgets.QPushButton(HastalikSilme)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mainmenubuton.sizePolicy().hasHeightForWidth())
        self.mainmenubuton.setSizePolicy(sizePolicy)
        self.mainmenubuton.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icons/home.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mainmenubuton.setIcon(icon3)
        self.mainmenubuton.setIconSize(QtCore.QSize(64, 64))
        self.mainmenubuton.setObjectName("mainmenubuton")
        self.horizontalLayout.addWidget(self.mainmenubuton)
        self.exitbuton = QtWidgets.QPushButton(HastalikSilme)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.exitbuton.sizePolicy().hasHeightForWidth())
        self.exitbuton.setSizePolicy(sizePolicy)
        self.exitbuton.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("icons/exits.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.exitbuton.setIcon(icon4)
        self.exitbuton.setIconSize(QtCore.QSize(64, 64))
        self.exitbuton.setObjectName("exitbuton")
        self.horizontalLayout.addWidget(self.exitbuton)
        self.gridLayout.addLayout(self.horizontalLayout, 8, 0, 1, 3)
        self.goatList = QtWidgets.QTableWidget(HastalikSilme)
        self.goatList.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.goatList.setDragDropOverwriteMode(False)
        self.goatList.setAlternatingRowColors(False)
        self.goatList.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.goatList.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.goatList.setRowCount(3)
        self.goatList.setColumnCount(3)
        self.goatList.setObjectName("goatList")
        self.gridLayout.addWidget(self.goatList, 1, 0, 3, 2)
        self.goatshow = QtWidgets.QLabel(HastalikSilme)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.goatshow.sizePolicy().hasHeightForWidth())
        self.goatshow.setSizePolicy(sizePolicy)
        self.goatshow.setMinimumSize(QtCore.QSize(100, 100))
        self.goatshow.setAutoFillBackground(False)
        self.goatshow.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.goatshow.setText("")
        self.goatshow.setPixmap(QtGui.QPixmap("icons/keçi.ico"))
        self.goatshow.setScaledContents(True)
        self.goatshow.setObjectName("goatshow")
        self.gridLayout.addWidget(self.goatshow, 1, 2, 3, 1)

        self.retranslateUi(HastalikSilme)
        QtCore.QMetaObject.connectSlotsByName(HastalikSilme)
        HastalikSilme.setTabOrder(self.goatList, self.acceptbuton)
        HastalikSilme.setTabOrder(self.acceptbuton, self.mainmenubuton)
        HastalikSilme.setTabOrder(self.mainmenubuton, self.exitbuton)

    def retranslateUi(self, HastalikSilme):
        _translate = QtCore.QCoreApplication.translate
        HastalikSilme.setWindowTitle(_translate("HastalikSilme", "Hastalık Sil"))
        self.label.setText(_translate("HastalikSilme", "Silinecek Hastalık Seçin:"))
        self.goatList.setSortingEnabled(True)
