# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'hastaliktanimlas.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_HastalikTanimla(object):
    def setupUi(self, HastalikTanimla):
        HastalikTanimla.setObjectName("HastalikTanimla")
        HastalikTanimla.resize(356, 296)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/keçi.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        HastalikTanimla.setWindowIcon(icon)
        self.gridLayout = QtWidgets.QGridLayout(HastalikTanimla)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.acceptbuton = QtWidgets.QPushButton(HastalikTanimla)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.acceptbuton.sizePolicy().hasHeightForWidth())
        self.acceptbuton.setSizePolicy(sizePolicy)
        self.acceptbuton.setMinimumSize(QtCore.QSize(100, 100))
        self.acceptbuton.setMaximumSize(QtCore.QSize(150, 150))
        self.acceptbuton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/tick.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.acceptbuton.setIcon(icon1)
        self.acceptbuton.setIconSize(QtCore.QSize(64, 64))
        self.acceptbuton.setObjectName("acceptbuton")
        self.horizontalLayout.addWidget(self.acceptbuton)
        self.mainmenubuton = QtWidgets.QPushButton(HastalikTanimla)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mainmenubuton.sizePolicy().hasHeightForWidth())
        self.mainmenubuton.setSizePolicy(sizePolicy)
        self.mainmenubuton.setMinimumSize(QtCore.QSize(100, 100))
        self.mainmenubuton.setMaximumSize(QtCore.QSize(150, 150))
        self.mainmenubuton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icons/home.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mainmenubuton.setIcon(icon2)
        self.mainmenubuton.setIconSize(QtCore.QSize(64, 64))
        self.mainmenubuton.setObjectName("mainmenubuton")
        self.horizontalLayout.addWidget(self.mainmenubuton)
        self.exitbuton = QtWidgets.QPushButton(HastalikTanimla)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.exitbuton.sizePolicy().hasHeightForWidth())
        self.exitbuton.setSizePolicy(sizePolicy)
        self.exitbuton.setMinimumSize(QtCore.QSize(100, 100))
        self.exitbuton.setMaximumSize(QtCore.QSize(150, 150))
        self.exitbuton.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icons/exits.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.exitbuton.setIcon(icon3)
        self.exitbuton.setIconSize(QtCore.QSize(64, 64))
        self.exitbuton.setObjectName("exitbuton")
        self.horizontalLayout.addWidget(self.exitbuton)
        self.gridLayout.addLayout(self.horizontalLayout, 4, 1, 1, 1)
        self.result = QtWidgets.QLabel(HastalikTanimla)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(15)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.result.setFont(font)
        self.result.setText("")
        self.result.setObjectName("result")
        self.gridLayout.addWidget(self.result, 3, 1, 1, 1)
        self.hastalik = QtWidgets.QLineEdit(HastalikTanimla)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.hastalik.setFont(font)
        self.hastalik.setObjectName("hastalik")
        self.gridLayout.addWidget(self.hastalik, 2, 1, 1, 1)
        self.label = QtWidgets.QLabel(HastalikTanimla)
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 1, 1, 1)

        self.retranslateUi(HastalikTanimla)
        QtCore.QMetaObject.connectSlotsByName(HastalikTanimla)
        HastalikTanimla.setTabOrder(self.mainmenubuton, self.exitbuton)

    def retranslateUi(self, HastalikTanimla):
        _translate = QtCore.QCoreApplication.translate
        HastalikTanimla.setWindowTitle(_translate("HastalikTanimla", "Hastalık Tanımla"))
        self.label.setText(_translate("HastalikTanimla", "Hastalığın Adını Giriniz"))
