# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'keciekles.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_KeciEkle(object):
    def setupUi(self, KeciEkle):
        KeciEkle.setObjectName("KeciEkle")
        KeciEkle.resize(475, 518)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/keçi.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        KeciEkle.setWindowIcon(icon)
        self.gridLayout = QtWidgets.QGridLayout(KeciEkle)
        self.gridLayout.setSpacing(20)
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtWidgets.QLabel(KeciEkle)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.disi = QtWidgets.QRadioButton(KeciEkle)
        self.disi.setObjectName("disi")
        self.gridLayout.addWidget(self.disi, 4, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(KeciEkle)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 4, 0, 1, 1)
        self.gozat = QtWidgets.QPushButton(KeciEkle)
        self.gozat.setObjectName("gozat")
        self.gridLayout.addWidget(self.gozat, 6, 1, 2, 1)
        self.birthdate = QtWidgets.QDateEdit(KeciEkle)
        self.birthdate.setCalendarPopup(True)
        self.birthdate.setCurrentSectionIndex(0)
        self.birthdate.setObjectName("birthdate")
        self.gridLayout.addWidget(self.birthdate, 3, 1, 1, 1)
        self.label = QtWidgets.QLabel(KeciEkle)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(KeciEkle)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(KeciEkle)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.goatshow = QtWidgets.QLabel(KeciEkle)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.goatshow.sizePolicy().hasHeightForWidth())
        self.goatshow.setSizePolicy(sizePolicy)
        self.goatshow.setMinimumSize(QtCore.QSize(100, 100))
        self.goatshow.setMaximumSize(QtCore.QSize(250, 250))
        self.goatshow.setAutoFillBackground(False)
        self.goatshow.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.goatshow.setFrameShadow(QtWidgets.QFrame.Plain)
        self.goatshow.setLineWidth(3)
        self.goatshow.setMidLineWidth(3)
        self.goatshow.setText("")
        self.goatshow.setPixmap(QtGui.QPixmap("icons/keçi.png"))
        self.goatshow.setScaledContents(True)
        self.goatshow.setObjectName("goatshow")
        self.gridLayout.addWidget(self.goatshow, 5, 2, 2, 1)
        self.erkek = QtWidgets.QRadioButton(KeciEkle)
        self.erkek.setObjectName("erkek")
        self.gridLayout.addWidget(self.erkek, 4, 1, 1, 1)
        self.kecituru = QtWidgets.QComboBox(KeciEkle)
        self.kecituru.setObjectName("kecituru")
        self.gridLayout.addWidget(self.kecituru, 5, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(KeciEkle)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 6, 0, 1, 1)
        self.kimlikno = QtWidgets.QLineEdit(KeciEkle)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.kimlikno.setFont(font)
        self.kimlikno.setObjectName("kimlikno")
        self.gridLayout.addWidget(self.kimlikno, 0, 1, 1, 2)
        self.result = QtWidgets.QLabel(KeciEkle)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.result.setFont(font)
        self.result.setText("")
        self.result.setObjectName("result")
        self.gridLayout.addWidget(self.result, 8, 0, 2, 2)
        self.label_6 = QtWidgets.QLabel(KeciEkle)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 5, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.acceptbuton = QtWidgets.QPushButton(KeciEkle)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.acceptbuton.sizePolicy().hasHeightForWidth())
        self.acceptbuton.setSizePolicy(sizePolicy)
        self.acceptbuton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/tick.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.acceptbuton.setIcon(icon1)
        self.acceptbuton.setIconSize(QtCore.QSize(64, 64))
        self.acceptbuton.setObjectName("acceptbuton")
        self.horizontalLayout.addWidget(self.acceptbuton)
        self.refreshbuton = QtWidgets.QPushButton(KeciEkle)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.refreshbuton.sizePolicy().hasHeightForWidth())
        self.refreshbuton.setSizePolicy(sizePolicy)
        self.refreshbuton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icons/refresh.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.refreshbuton.setIcon(icon2)
        self.refreshbuton.setIconSize(QtCore.QSize(64, 64))
        self.refreshbuton.setCheckable(False)
        self.refreshbuton.setChecked(False)
        self.refreshbuton.setAutoRepeat(False)
        self.refreshbuton.setAutoDefault(False)
        self.refreshbuton.setDefault(False)
        self.refreshbuton.setFlat(False)
        self.refreshbuton.setObjectName("refreshbuton")
        self.horizontalLayout.addWidget(self.refreshbuton)
        self.mainmenubuton = QtWidgets.QPushButton(KeciEkle)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mainmenubuton.sizePolicy().hasHeightForWidth())
        self.mainmenubuton.setSizePolicy(sizePolicy)
        self.mainmenubuton.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icons/home.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mainmenubuton.setIcon(icon3)
        self.mainmenubuton.setIconSize(QtCore.QSize(64, 64))
        self.mainmenubuton.setObjectName("mainmenubuton")
        self.horizontalLayout.addWidget(self.mainmenubuton)
        self.exitbuton = QtWidgets.QPushButton(KeciEkle)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.exitbuton.sizePolicy().hasHeightForWidth())
        self.exitbuton.setSizePolicy(sizePolicy)
        self.exitbuton.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("icons/exits.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.exitbuton.setIcon(icon4)
        self.exitbuton.setIconSize(QtCore.QSize(64, 64))
        self.exitbuton.setObjectName("exitbuton")
        self.horizontalLayout.addWidget(self.exitbuton)
        self.gridLayout.addLayout(self.horizontalLayout, 10, 0, 1, 3)
        self.annekimlik = QtWidgets.QComboBox(KeciEkle)
        self.annekimlik.setEditable(True)
        self.annekimlik.setObjectName("annekimlik")
        self.gridLayout.addWidget(self.annekimlik, 1, 1, 1, 2)
        self.babakimlik = QtWidgets.QComboBox(KeciEkle)
        self.babakimlik.setEditable(True)
        self.babakimlik.setObjectName("babakimlik")
        self.gridLayout.addWidget(self.babakimlik, 2, 1, 1, 2)

        self.retranslateUi(KeciEkle)
        QtCore.QMetaObject.connectSlotsByName(KeciEkle)
        KeciEkle.setTabOrder(self.kimlikno, self.birthdate)
        KeciEkle.setTabOrder(self.birthdate, self.erkek)
        KeciEkle.setTabOrder(self.erkek, self.disi)
        KeciEkle.setTabOrder(self.disi, self.kecituru)
        KeciEkle.setTabOrder(self.kecituru, self.gozat)
        KeciEkle.setTabOrder(self.gozat, self.acceptbuton)
        KeciEkle.setTabOrder(self.acceptbuton, self.refreshbuton)
        KeciEkle.setTabOrder(self.refreshbuton, self.mainmenubuton)
        KeciEkle.setTabOrder(self.mainmenubuton, self.exitbuton)

    def retranslateUi(self, KeciEkle):
        _translate = QtCore.QCoreApplication.translate
        KeciEkle.setWindowTitle(_translate("KeciEkle", "Keçi EKLE"))
        self.label_3.setText(_translate("KeciEkle", "Baba Kimlik No:"))
        self.disi.setText(_translate("KeciEkle", "Dişi"))
        self.label_5.setText(_translate("KeciEkle", "Cinsiyet"))
        self.gozat.setText(_translate("KeciEkle", "Gözat"))
        self.label.setText(_translate("KeciEkle", "Keçi Kimlik No:"))
        self.label_4.setText(_translate("KeciEkle", "Doğum Tarihi:"))
        self.label_2.setText(_translate("KeciEkle", "Anne Kimlik No:"))
        self.erkek.setText(_translate("KeciEkle", "Erkek"))
        self.label_7.setText(_translate("KeciEkle", "Keçi Fotoğrafı Seçin"))
        self.label_6.setText(_translate("KeciEkle", "Keçi Türü"))
