# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainmenus.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AnaMenu(object):
    def setupUi(self, AnaMenu):
        AnaMenu.setObjectName("AnaMenu")
        AnaMenu.setWindowModality(QtCore.Qt.NonModal)
        AnaMenu.resize(800, 600)
        AnaMenu.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/keçi.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        AnaMenu.setWindowIcon(icon)
        AnaMenu.setAutoFillBackground(False)
        AnaMenu.setDocumentMode(False)
        AnaMenu.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(AnaMenu)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(-1, -1, -1, 50)
        self.gridLayout.setHorizontalSpacing(50)
        self.gridLayout.setVerticalSpacing(20)
        self.gridLayout.setObjectName("gridLayout")
        self.silbuton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.silbuton.sizePolicy().hasHeightForWidth())
        self.silbuton.setSizePolicy(sizePolicy)
        self.silbuton.setMinimumSize(QtCore.QSize(250, 125))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.silbuton.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/minus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.silbuton.setIcon(icon1)
        self.silbuton.setIconSize(QtCore.QSize(64, 64))
        self.silbuton.setObjectName("silbuton")
        self.gridLayout.addWidget(self.silbuton, 2, 2, 1, 1)
        self.raporlabuton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.raporlabuton.sizePolicy().hasHeightForWidth())
        self.raporlabuton.setSizePolicy(sizePolicy)
        self.raporlabuton.setMinimumSize(QtCore.QSize(250, 125))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.raporlabuton.setFont(font)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icons/report.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.raporlabuton.setIcon(icon2)
        self.raporlabuton.setIconSize(QtCore.QSize(64, 64))
        self.raporlabuton.setObjectName("raporlabuton")
        self.gridLayout.addWidget(self.raporlabuton, 6, 1, 1, 1)
        self.tanimlabuton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tanimlabuton.sizePolicy().hasHeightForWidth())
        self.tanimlabuton.setSizePolicy(sizePolicy)
        self.tanimlabuton.setMinimumSize(QtCore.QSize(250, 125))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.tanimlabuton.setFont(font)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icons/tanim.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tanimlabuton.setIcon(icon3)
        self.tanimlabuton.setIconSize(QtCore.QSize(64, 64))
        self.tanimlabuton.setObjectName("tanimlabuton")
        self.gridLayout.addWidget(self.tanimlabuton, 3, 2, 1, 1)
        self.duzenlebuton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.duzenlebuton.sizePolicy().hasHeightForWidth())
        self.duzenlebuton.setSizePolicy(sizePolicy)
        self.duzenlebuton.setMinimumSize(QtCore.QSize(250, 125))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.duzenlebuton.setFont(font)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("icons/edit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.duzenlebuton.setIcon(icon4)
        self.duzenlebuton.setIconSize(QtCore.QSize(64, 64))
        self.duzenlebuton.setObjectName("duzenlebuton")
        self.gridLayout.addWidget(self.duzenlebuton, 3, 1, 1, 1)
        self.eklebuton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.eklebuton.sizePolicy().hasHeightForWidth())
        self.eklebuton.setSizePolicy(sizePolicy)
        self.eklebuton.setMinimumSize(QtCore.QSize(250, 125))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.eklebuton.setFont(font)
        self.eklebuton.setToolTipDuration(-1)
        self.eklebuton.setStatusTip("")
        self.eklebuton.setWhatsThis("")
        self.eklebuton.setAccessibleName("")
        self.eklebuton.setAccessibleDescription("")
        self.eklebuton.setStyleSheet("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("icons/plus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.eklebuton.setIcon(icon5)
        self.eklebuton.setIconSize(QtCore.QSize(64, 64))
        self.eklebuton.setObjectName("eklebuton")
        self.gridLayout.addWidget(self.eklebuton, 2, 1, 1, 1)
        self.anabaslik = QtWidgets.QLabel(self.centralwidget)
        self.anabaslik.setTextFormat(QtCore.Qt.AutoText)
        self.anabaslik.setScaledContents(False)
        self.anabaslik.setObjectName("anabaslik")
        self.gridLayout.addWidget(self.anabaslik, 0, 0, 1, 4)
        self.cikisbuton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cikisbuton.sizePolicy().hasHeightForWidth())
        self.cikisbuton.setSizePolicy(sizePolicy)
        self.cikisbuton.setMinimumSize(QtCore.QSize(250, 125))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.cikisbuton.setFont(font)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("icons/exits.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cikisbuton.setIcon(icon6)
        self.cikisbuton.setIconSize(QtCore.QSize(64, 64))
        self.cikisbuton.setObjectName("cikisbuton")
        self.gridLayout.addWidget(self.cikisbuton, 6, 2, 1, 1)
        self.altbaslik = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.altbaslik.sizePolicy().hasHeightForWidth())
        self.altbaslik.setSizePolicy(sizePolicy)
        self.altbaslik.setObjectName("altbaslik")
        self.gridLayout.addWidget(self.altbaslik, 1, 1, 1, 2)
        AnaMenu.setCentralWidget(self.centralwidget)

        self.retranslateUi(AnaMenu)
        QtCore.QMetaObject.connectSlotsByName(AnaMenu)

    def retranslateUi(self, AnaMenu):
        _translate = QtCore.QCoreApplication.translate
        AnaMenu.setWindowTitle(_translate("AnaMenu", "Keçi Takip Programı Ver. 0.01"))
        self.silbuton.setText(_translate("AnaMenu", "SİL"))
        self.raporlabuton.setText(_translate("AnaMenu", "RAPORLA"))
        self.tanimlabuton.setText(_translate("AnaMenu", "TANIMLA"))
        self.duzenlebuton.setText(_translate("AnaMenu", "DÜZENLE"))
        self.eklebuton.setToolTip(_translate("AnaMenu", "<html><head/><body><p>Keçi Ekle</p><p>Aşım Tarihi Ekle</p><p>Süt Verimi Ekle</p><p>Kilo Bilgisi Ekle</p><p>Hastalık Durumu Ekle</p><p>Aşı Durumu Ekle</p></body></html>"))
        self.eklebuton.setText(_translate("AnaMenu", "EKLE"))
        self.anabaslik.setText(_translate("AnaMenu", "<html><head/><body><p align=\"center\"><span style=\" font-size:28pt; font-weight:600; color:#912c2c;\">Keçi Takip Programına Hoş Geldiniz</span></p></body></html>"))
        self.cikisbuton.setText(_translate("AnaMenu", "ÇIKIŞ"))
        self.altbaslik.setText(_translate("AnaMenu", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; font-weight:600;\">Yapmak İstediğiniz İşlemi Seçin</span></p></body></html>"))
