# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'reportmenus.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RaporlaMenu(object):
    def setupUi(self, RaporlaMenu):
        RaporlaMenu.setObjectName("RaporlaMenu")
        RaporlaMenu.resize(1280, 720)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/keçi.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        RaporlaMenu.setWindowIcon(icon)
        RaporlaMenu.setStyleSheet("")
        self.gridLayout = QtWidgets.QGridLayout(RaporlaMenu)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(30, 200, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.gridLayout.addItem(spacerItem, 9, 4, 1, 1)
        self.result = QtWidgets.QLabel(RaporlaMenu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.result.sizePolicy().hasHeightForWidth())
        self.result.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(15)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.result.setFont(font)
        self.result.setText("")
        self.result.setObjectName("result")
        self.gridLayout.addWidget(self.result, 8, 4, 1, 1)
        self.refreshbuton = QtWidgets.QPushButton(RaporlaMenu)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/refresh.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.refreshbuton.setIcon(icon1)
        self.refreshbuton.setObjectName("refreshbuton")
        self.gridLayout.addWidget(self.refreshbuton, 1, 4, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(RaporlaMenu)
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setStyleSheet("")
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget.setUsesScrollButtons(True)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setMovable(False)
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.goatlist = QtWidgets.QWidget()
        self.goatlist.setObjectName("goatlist")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.goatlist)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.goats = QtWidgets.QTableWidget(self.goatlist)
        self.goats.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.goats.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.goats.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.goats.setAlternatingRowColors(True)
        self.goats.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectItems)
        self.goats.setObjectName("goats")
        self.goats.setColumnCount(7)
        self.goats.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.goats.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.goats.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.goats.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.goats.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.goats.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.goats.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.goats.setHorizontalHeaderItem(6, item)
        self.gridLayout_3.addWidget(self.goats, 0, 0, 1, 1)
        self.tabWidget.addTab(self.goatlist, "")
        self.vaccinereport = QtWidgets.QWidget()
        self.vaccinereport.setObjectName("vaccinereport")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.vaccinereport)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.vaccines = QtWidgets.QTableWidget(self.vaccinereport)
        self.vaccines.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.vaccines.setAlternatingRowColors(True)
        self.vaccines.setObjectName("vaccines")
        self.vaccines.setColumnCount(3)
        self.vaccines.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.vaccines.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.vaccines.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.vaccines.setHorizontalHeaderItem(2, item)
        self.gridLayout_4.addWidget(self.vaccines, 0, 0, 1, 1)
        self.tabWidget.addTab(self.vaccinereport, "")
        self.sicksreport = QtWidgets.QWidget()
        self.sicksreport.setObjectName("sicksreport")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.sicksreport)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.sicks = QtWidgets.QTableWidget(self.sicksreport)
        self.sicks.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.sicks.setAlternatingRowColors(True)
        self.sicks.setObjectName("sicks")
        self.sicks.setColumnCount(4)
        self.sicks.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.sicks.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.sicks.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.sicks.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.sicks.setHorizontalHeaderItem(3, item)
        self.gridLayout_5.addWidget(self.sicks, 0, 0, 1, 1)
        self.tabWidget.addTab(self.sicksreport, "")
        self.milkreport = QtWidgets.QWidget()
        self.milkreport.setObjectName("milkreport")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.milkreport)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.milk = QtWidgets.QTableWidget(self.milkreport)
        self.milk.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.milk.setAlternatingRowColors(True)
        self.milk.setObjectName("milk")
        self.milk.setColumnCount(3)
        self.milk.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.milk.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.milk.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.milk.setHorizontalHeaderItem(2, item)
        self.gridLayout_7.addWidget(self.milk, 0, 0, 1, 1)
        self.tabWidget.addTab(self.milkreport, "")
        self.weightreport = QtWidgets.QWidget()
        self.weightreport.setObjectName("weightreport")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.weightreport)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.weight = QtWidgets.QTableWidget(self.weightreport)
        self.weight.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.weight.setAlternatingRowColors(True)
        self.weight.setObjectName("weight")
        self.weight.setColumnCount(3)
        self.weight.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.weight.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.weight.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.weight.setHorizontalHeaderItem(2, item)
        self.gridLayout_2.addWidget(self.weight, 0, 0, 1, 1)
        self.tabWidget.addTab(self.weightreport, "")
        self.deletereport = QtWidgets.QWidget()
        self.deletereport.setObjectName("deletereport")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.deletereport)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.deleted = QtWidgets.QTableWidget(self.deletereport)
        self.deleted.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.deleted.setAlternatingRowColors(True)
        self.deleted.setObjectName("deleted")
        self.deleted.setColumnCount(9)
        self.deleted.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.deleted.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.deleted.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.deleted.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.deleted.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.deleted.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.deleted.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.deleted.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.deleted.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.deleted.setHorizontalHeaderItem(8, item)
        self.gridLayout_6.addWidget(self.deleted, 0, 0, 1, 1)
        self.tabWidget.addTab(self.deletereport, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 6, 11, 1)
        self.groupBox = QtWidgets.QGroupBox(RaporlaMenu)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 175))
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout_8.addWidget(self.label_2, 3, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(10, 0))
        self.label.setMaximumSize(QtCore.QSize(10, 16777215))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout_8.addWidget(self.label, 4, 1, 1, 1)
        self.firstDate = QtWidgets.QDateEdit(self.groupBox)
        self.firstDate.setCalendarPopup(True)
        self.firstDate.setObjectName("firstDate")
        self.gridLayout_8.addWidget(self.firstDate, 4, 0, 1, 1)
        self.columns = QtWidgets.QComboBox(self.groupBox)
        self.columns.setObjectName("columns")
        self.gridLayout_8.addWidget(self.columns, 1, 0, 1, 3)
        self.secondDate = QtWidgets.QDateEdit(self.groupBox)
        self.secondDate.setCalendarPopup(True)
        self.secondDate.setObjectName("secondDate")
        self.gridLayout_8.addWidget(self.secondDate, 4, 2, 1, 1)
        self.filterbuton = QtWidgets.QPushButton(self.groupBox)
        self.filterbuton.setObjectName("filterbuton")
        self.gridLayout_8.addWidget(self.filterbuton, 5, 0, 1, 3)
        self.filtertext = QtWidgets.QLineEdit(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.filtertext.sizePolicy().hasHeightForWidth())
        self.filtertext.setSizePolicy(sizePolicy)
        self.filtertext.setReadOnly(False)
        self.filtertext.setClearButtonEnabled(True)
        self.filtertext.setObjectName("filtertext")
        self.gridLayout_8.addWidget(self.filtertext, 2, 0, 1, 3)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.gridLayout_8.addWidget(self.label_3, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox, 6, 4, 1, 1)
        self.goatshow = QtWidgets.QLabel(RaporlaMenu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.goatshow.sizePolicy().hasHeightForWidth())
        self.goatshow.setSizePolicy(sizePolicy)
        self.goatshow.setMinimumSize(QtCore.QSize(240, 240))
        self.goatshow.setMaximumSize(QtCore.QSize(240, 240))
        self.goatshow.setAutoFillBackground(False)
        self.goatshow.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.goatshow.setText("")
        self.goatshow.setPixmap(QtGui.QPixmap("icons/keçi.ico"))
        self.goatshow.setScaledContents(True)
        self.goatshow.setObjectName("goatshow")
        self.gridLayout.addWidget(self.goatshow, 0, 4, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.acceptbuton = QtWidgets.QPushButton(RaporlaMenu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.acceptbuton.sizePolicy().hasHeightForWidth())
        self.acceptbuton.setSizePolicy(sizePolicy)
        self.acceptbuton.setMaximumSize(QtCore.QSize(150, 150))
        self.acceptbuton.setStyleSheet("")
        self.acceptbuton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icons/tick.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.acceptbuton.setIcon(icon2)
        self.acceptbuton.setIconSize(QtCore.QSize(64, 64))
        self.acceptbuton.setObjectName("acceptbuton")
        self.horizontalLayout.addWidget(self.acceptbuton)
        self.mainmenubuton = QtWidgets.QPushButton(RaporlaMenu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mainmenubuton.sizePolicy().hasHeightForWidth())
        self.mainmenubuton.setSizePolicy(sizePolicy)
        self.mainmenubuton.setMaximumSize(QtCore.QSize(150, 150))
        self.mainmenubuton.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icons/home.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mainmenubuton.setIcon(icon3)
        self.mainmenubuton.setIconSize(QtCore.QSize(64, 64))
        self.mainmenubuton.setObjectName("mainmenubuton")
        self.horizontalLayout.addWidget(self.mainmenubuton)
        self.exitbuton = QtWidgets.QPushButton(RaporlaMenu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.exitbuton.sizePolicy().hasHeightForWidth())
        self.exitbuton.setSizePolicy(sizePolicy)
        self.exitbuton.setMaximumSize(QtCore.QSize(150, 150))
        self.exitbuton.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("icons/exits.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.exitbuton.setIcon(icon4)
        self.exitbuton.setIconSize(QtCore.QSize(64, 64))
        self.exitbuton.setObjectName("exitbuton")
        self.horizontalLayout.addWidget(self.exitbuton)
        self.gridLayout.addLayout(self.horizontalLayout, 10, 4, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(RaporlaMenu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setMinimumSize(QtCore.QSize(150, 0))
        self.groupBox_2.setStyleSheet("QLineEdit {background-color: #FAFF9C;\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: white;\n"
"    padding: 3px;\n"
"}")
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_9.setSpacing(6)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.label_10 = QtWidgets.QLabel(self.groupBox_2)
        self.label_10.setObjectName("label_10")
        self.gridLayout_9.addWidget(self.label_10, 9, 0, 1, 1)
        self.aylik_asi = QtWidgets.QLineEdit(self.groupBox_2)
        self.aylik_asi.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.aylik_asi.sizePolicy().hasHeightForWidth())
        self.aylik_asi.setSizePolicy(sizePolicy)
        self.aylik_asi.setMinimumSize(QtCore.QSize(0, 0))
        self.aylik_asi.setMaximumSize(QtCore.QSize(50, 20))
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.aylik_asi.setFont(font)
        self.aylik_asi.setObjectName("aylik_asi")
        self.gridLayout_9.addWidget(self.aylik_asi, 4, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setObjectName("label_4")
        self.gridLayout_9.addWidget(self.label_4, 0, 0, 1, 1)
        self.asim_yaklasan = QtWidgets.QLineEdit(self.groupBox_2)
        self.asim_yaklasan.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.asim_yaklasan.sizePolicy().hasHeightForWidth())
        self.asim_yaklasan.setSizePolicy(sizePolicy)
        self.asim_yaklasan.setMinimumSize(QtCore.QSize(0, 0))
        self.asim_yaklasan.setMaximumSize(QtCore.QSize(50, 20))
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.asim_yaklasan.setFont(font)
        self.asim_yaklasan.setObjectName("asim_yaklasan")
        self.gridLayout_9.addWidget(self.asim_yaklasan, 3, 1, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.groupBox_2)
        self.label_15.setObjectName("label_15")
        self.gridLayout_9.addWidget(self.label_15, 7, 0, 1, 1)
        self.silinen_keci = QtWidgets.QLineEdit(self.groupBox_2)
        self.silinen_keci.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.silinen_keci.sizePolicy().hasHeightForWidth())
        self.silinen_keci.setSizePolicy(sizePolicy)
        self.silinen_keci.setMinimumSize(QtCore.QSize(0, 0))
        self.silinen_keci.setMaximumSize(QtCore.QSize(50, 20))
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.silinen_keci.setFont(font)
        self.silinen_keci.setObjectName("silinen_keci")
        self.gridLayout_9.addWidget(self.silinen_keci, 10, 1, 1, 1)
        self.hasta_keci = QtWidgets.QLineEdit(self.groupBox_2)
        self.hasta_keci.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hasta_keci.sizePolicy().hasHeightForWidth())
        self.hasta_keci.setSizePolicy(sizePolicy)
        self.hasta_keci.setMinimumSize(QtCore.QSize(0, 0))
        self.hasta_keci.setMaximumSize(QtCore.QSize(50, 20))
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.hasta_keci.setFont(font)
        self.hasta_keci.setObjectName("hasta_keci")
        self.gridLayout_9.addWidget(self.hasta_keci, 5, 1, 1, 1)
        self.keci_sayisi = QtWidgets.QLineEdit(self.groupBox_2)
        self.keci_sayisi.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.keci_sayisi.sizePolicy().hasHeightForWidth())
        self.keci_sayisi.setSizePolicy(sizePolicy)
        self.keci_sayisi.setMinimumSize(QtCore.QSize(0, 0))
        self.keci_sayisi.setMaximumSize(QtCore.QSize(50, 20))
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.keci_sayisi.setFont(font)
        self.keci_sayisi.setObjectName("keci_sayisi")
        self.gridLayout_9.addWidget(self.keci_sayisi, 0, 1, 1, 1)
        self.cogunluk_cinsi = QtWidgets.QLineEdit(self.groupBox_2)
        self.cogunluk_cinsi.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cogunluk_cinsi.sizePolicy().hasHeightForWidth())
        self.cogunluk_cinsi.setSizePolicy(sizePolicy)
        self.cogunluk_cinsi.setMinimumSize(QtCore.QSize(0, 0))
        self.cogunluk_cinsi.setMaximumSize(QtCore.QSize(50, 20))
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.cogunluk_cinsi.setFont(font)
        self.cogunluk_cinsi.setObjectName("cogunluk_cinsi")
        self.gridLayout_9.addWidget(self.cogunluk_cinsi, 2, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBox_2)
        self.label_9.setObjectName("label_9")
        self.gridLayout_9.addWidget(self.label_9, 4, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.groupBox_2)
        self.label_13.setObjectName("label_13")
        self.gridLayout_9.addWidget(self.label_13, 10, 0, 1, 1)
        self.iyilesen_keci = QtWidgets.QLineEdit(self.groupBox_2)
        self.iyilesen_keci.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.iyilesen_keci.sizePolicy().hasHeightForWidth())
        self.iyilesen_keci.setSizePolicy(sizePolicy)
        self.iyilesen_keci.setMinimumSize(QtCore.QSize(0, 0))
        self.iyilesen_keci.setMaximumSize(QtCore.QSize(50, 20))
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.iyilesen_keci.setFont(font)
        self.iyilesen_keci.setObjectName("iyilesen_keci")
        self.gridLayout_9.addWidget(self.iyilesen_keci, 6, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setObjectName("label_6")
        self.gridLayout_9.addWidget(self.label_6, 2, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        self.label_8.setObjectName("label_8")
        self.gridLayout_9.addWidget(self.label_8, 3, 0, 1, 1)
        self.ort_kecikutlesi = QtWidgets.QLineEdit(self.groupBox_2)
        self.ort_kecikutlesi.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ort_kecikutlesi.sizePolicy().hasHeightForWidth())
        self.ort_kecikutlesi.setSizePolicy(sizePolicy)
        self.ort_kecikutlesi.setMinimumSize(QtCore.QSize(0, 0))
        self.ort_kecikutlesi.setMaximumSize(QtCore.QSize(50, 20))
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.ort_kecikutlesi.setFont(font)
        self.ort_kecikutlesi.setObjectName("ort_kecikutlesi")
        self.gridLayout_9.addWidget(self.ort_kecikutlesi, 9, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setObjectName("label_5")
        self.gridLayout_9.addWidget(self.label_5, 1, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setObjectName("label_7")
        self.gridLayout_9.addWidget(self.label_7, 5, 0, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.groupBox_2)
        self.label_14.setObjectName("label_14")
        self.gridLayout_9.addWidget(self.label_14, 11, 0, 1, 1)
        self.ort_keciyasi = QtWidgets.QLineEdit(self.groupBox_2)
        self.ort_keciyasi.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ort_keciyasi.sizePolicy().hasHeightForWidth())
        self.ort_keciyasi.setSizePolicy(sizePolicy)
        self.ort_keciyasi.setMinimumSize(QtCore.QSize(0, 0))
        self.ort_keciyasi.setMaximumSize(QtCore.QSize(50, 20))
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.ort_keciyasi.setFont(font)
        self.ort_keciyasi.setObjectName("ort_keciyasi")
        self.gridLayout_9.addWidget(self.ort_keciyasi, 11, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.groupBox_2)
        self.label_11.setObjectName("label_11")
        self.gridLayout_9.addWidget(self.label_11, 8, 0, 1, 1)
        self.gunluk_sut = QtWidgets.QLineEdit(self.groupBox_2)
        self.gunluk_sut.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gunluk_sut.sizePolicy().hasHeightForWidth())
        self.gunluk_sut.setSizePolicy(sizePolicy)
        self.gunluk_sut.setMinimumSize(QtCore.QSize(0, 0))
        self.gunluk_sut.setMaximumSize(QtCore.QSize(50, 20))
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.gunluk_sut.setFont(font)
        self.gunluk_sut.setObjectName("gunluk_sut")
        self.gridLayout_9.addWidget(self.gunluk_sut, 7, 1, 1, 1)
        self.erkekdisi_orani = QtWidgets.QLineEdit(self.groupBox_2)
        self.erkekdisi_orani.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.erkekdisi_orani.sizePolicy().hasHeightForWidth())
        self.erkekdisi_orani.setSizePolicy(sizePolicy)
        self.erkekdisi_orani.setMinimumSize(QtCore.QSize(0, 0))
        self.erkekdisi_orani.setMaximumSize(QtCore.QSize(50, 20))
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.erkekdisi_orani.setFont(font)
        self.erkekdisi_orani.setObjectName("erkekdisi_orani")
        self.gridLayout_9.addWidget(self.erkekdisi_orani, 1, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.groupBox_2)
        self.label_12.setObjectName("label_12")
        self.gridLayout_9.addWidget(self.label_12, 6, 0, 1, 1)
        self.aylik_sut = QtWidgets.QLineEdit(self.groupBox_2)
        self.aylik_sut.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.aylik_sut.sizePolicy().hasHeightForWidth())
        self.aylik_sut.setSizePolicy(sizePolicy)
        self.aylik_sut.setMinimumSize(QtCore.QSize(0, 0))
        self.aylik_sut.setMaximumSize(QtCore.QSize(50, 20))
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.aylik_sut.setFont(font)
        self.aylik_sut.setObjectName("aylik_sut")
        self.gridLayout_9.addWidget(self.aylik_sut, 8, 1, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_3.setMaximumSize(QtCore.QSize(200, 150))
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_16 = QtWidgets.QLabel(self.groupBox_3)
        self.label_16.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_16.setObjectName("label_16")
        self.verticalLayout.addWidget(self.label_16)
        self.graphicType = QtWidgets.QComboBox(self.groupBox_3)
        self.graphicType.setObjectName("graphicType")
        self.graphicType.addItem("")
        self.verticalLayout.addWidget(self.graphicType)
        self.createGraphic = QtWidgets.QPushButton(self.groupBox_3)
        self.createGraphic.setObjectName("createGraphic")
        self.verticalLayout.addWidget(self.createGraphic)
        self.gridLayout_9.addWidget(self.groupBox_3, 12, 0, 1, 2)
        self.gridLayout.addWidget(self.groupBox_2, 0, 7, 11, 1)

        self.retranslateUi(RaporlaMenu)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(RaporlaMenu)
        RaporlaMenu.setTabOrder(self.tabWidget, self.goats)
        RaporlaMenu.setTabOrder(self.goats, self.vaccines)
        RaporlaMenu.setTabOrder(self.vaccines, self.sicks)
        RaporlaMenu.setTabOrder(self.sicks, self.milk)
        RaporlaMenu.setTabOrder(self.milk, self.weight)
        RaporlaMenu.setTabOrder(self.weight, self.deleted)
        RaporlaMenu.setTabOrder(self.deleted, self.acceptbuton)
        RaporlaMenu.setTabOrder(self.acceptbuton, self.mainmenubuton)
        RaporlaMenu.setTabOrder(self.mainmenubuton, self.exitbuton)

    def retranslateUi(self, RaporlaMenu):
        _translate = QtCore.QCoreApplication.translate
        RaporlaMenu.setWindowTitle(_translate("RaporlaMenu", "Raporlama Ekranı"))
        self.refreshbuton.setText(_translate("RaporlaMenu", "Yenile"))
        self.goats.setSortingEnabled(True)
        item = self.goats.horizontalHeaderItem(0)
        item.setText(_translate("RaporlaMenu", "Keçi ID"))
        item = self.goats.horizontalHeaderItem(1)
        item.setText(_translate("RaporlaMenu", "Baba ID"))
        item = self.goats.horizontalHeaderItem(2)
        item.setText(_translate("RaporlaMenu", "Anne ID"))
        item = self.goats.horizontalHeaderItem(3)
        item.setText(_translate("RaporlaMenu", "Doğum Tarihi"))
        item = self.goats.horizontalHeaderItem(4)
        item.setText(_translate("RaporlaMenu", "Cinsiyeti"))
        item = self.goats.horizontalHeaderItem(5)
        item.setText(_translate("RaporlaMenu", "Cinsi"))
        item = self.goats.horizontalHeaderItem(6)
        item.setText(_translate("RaporlaMenu", "Aşım Zamanı"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.goatlist), _translate("RaporlaMenu", "Keçi Listesi"))
        self.vaccines.setSortingEnabled(True)
        item = self.vaccines.horizontalHeaderItem(0)
        item.setText(_translate("RaporlaMenu", "Keçi ID"))
        item = self.vaccines.horizontalHeaderItem(1)
        item.setText(_translate("RaporlaMenu", "Aşı"))
        item = self.vaccines.horizontalHeaderItem(2)
        item.setText(_translate("RaporlaMenu", "Yapılma Tarihi"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.vaccinereport), _translate("RaporlaMenu", "Aşı Durumu"))
        self.sicks.setSortingEnabled(True)
        item = self.sicks.horizontalHeaderItem(0)
        item.setText(_translate("RaporlaMenu", "Keçi ID"))
        item = self.sicks.horizontalHeaderItem(1)
        item.setText(_translate("RaporlaMenu", "Hastalık"))
        item = self.sicks.horizontalHeaderItem(2)
        item.setText(_translate("RaporlaMenu", "Başlangıç Tarihi"))
        item = self.sicks.horizontalHeaderItem(3)
        item.setText(_translate("RaporlaMenu", "Bitiş Tarihi"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.sicksreport), _translate("RaporlaMenu", "Hastalık Durumu"))
        self.milk.setSortingEnabled(True)
        item = self.milk.horizontalHeaderItem(0)
        item.setText(_translate("RaporlaMenu", "Keçi ID"))
        item = self.milk.horizontalHeaderItem(1)
        item.setText(_translate("RaporlaMenu", "Süt Miktarı (KG)"))
        item = self.milk.horizontalHeaderItem(2)
        item.setText(_translate("RaporlaMenu", "Tarih"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.milkreport), _translate("RaporlaMenu", "Süt Verimi"))
        self.weight.setSortingEnabled(True)
        item = self.weight.horizontalHeaderItem(0)
        item.setText(_translate("RaporlaMenu", "Keçi ID"))
        item = self.weight.horizontalHeaderItem(1)
        item.setText(_translate("RaporlaMenu", "Kütle (KG)"))
        item = self.weight.horizontalHeaderItem(2)
        item.setText(_translate("RaporlaMenu", "Tarih"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.weightreport), _translate("RaporlaMenu", "Kilo Durumları"))
        self.deleted.setSortingEnabled(True)
        item = self.deleted.horizontalHeaderItem(0)
        item.setText(_translate("RaporlaMenu", "Silinen Keçi ID"))
        item = self.deleted.horizontalHeaderItem(1)
        item.setText(_translate("RaporlaMenu", "Baba ID"))
        item = self.deleted.horizontalHeaderItem(2)
        item.setText(_translate("RaporlaMenu", "Anne ID"))
        item = self.deleted.horizontalHeaderItem(3)
        item.setText(_translate("RaporlaMenu", "Doğum Tarihi"))
        item = self.deleted.horizontalHeaderItem(4)
        item.setText(_translate("RaporlaMenu", "Cinsiyeti"))
        item = self.deleted.horizontalHeaderItem(5)
        item.setText(_translate("RaporlaMenu", "Cinsi"))
        item = self.deleted.horizontalHeaderItem(6)
        item.setText(_translate("RaporlaMenu", "Aşım Zamanı"))
        item = self.deleted.horizontalHeaderItem(7)
        item.setText(_translate("RaporlaMenu", "Silinme Sebebi"))
        item = self.deleted.horizontalHeaderItem(8)
        item.setText(_translate("RaporlaMenu", "Silinme Tarihi"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.deletereport), _translate("RaporlaMenu", "Silinen Keçiler"))
        self.groupBox.setTitle(_translate("RaporlaMenu", "Filtreleme"))
        self.label_2.setText(_translate("RaporlaMenu", "Tarih Aralığı Seçin"))
        self.label.setText(_translate("RaporlaMenu", "-"))
        self.filterbuton.setText(_translate("RaporlaMenu", "Filtrele"))
        self.filtertext.setPlaceholderText(_translate("RaporlaMenu", "Filtrelenecek Metni Girin"))
        self.label_3.setText(_translate("RaporlaMenu", "Filtrelenecek Kolon"))
        self.groupBox_2.setTitle(_translate("RaporlaMenu", "Durum Bilgileri"))
        self.label_10.setText(_translate("RaporlaMenu", "Ortalama Keçi Kütlesi:"))
        self.label_4.setText(_translate("RaporlaMenu", "Keçi Sayısı:"))
        self.label_15.setText(_translate("RaporlaMenu", "Günlük Süt Miktarı:"))
        self.silinen_keci.setText(_translate("RaporlaMenu", "30"))
        self.label_9.setText(_translate("RaporlaMenu", "Bu Ay Yapılan Aşı:"))
        self.label_13.setText(_translate("RaporlaMenu", "Silinen Keçi Sayısı:"))
        self.label_6.setText(_translate("RaporlaMenu", "Çoğunluk Cinsi:"))
        self.label_8.setText(_translate("RaporlaMenu", "Aşım Zamanı Yaklaşan:"))
        self.label_5.setText(_translate("RaporlaMenu", "Erkek/Dişi Oranı"))
        self.label_7.setText(_translate("RaporlaMenu", "Hasta Keçi:"))
        self.label_14.setText(_translate("RaporlaMenu", "Ortalama Keçi Yaşı:"))
        self.ort_keciyasi.setText(_translate("RaporlaMenu", "25"))
        self.label_11.setText(_translate("RaporlaMenu", "Aylık Süt Miktarı:"))
        self.label_12.setText(_translate("RaporlaMenu", "İyileşen Keçi:"))
        self.groupBox_3.setTitle(_translate("RaporlaMenu", "Grafik Oluşturma"))
        self.label_16.setText(_translate("RaporlaMenu", "Grafik Türünü Seçin:"))
        self.graphicType.setItemText(0, _translate("RaporlaMenu", "Aylara Göre Süt Verim Grafiği"))
        self.createGraphic.setText(_translate("RaporlaMenu", "Grafiği Oluştur"))
